### ISSUE TITLE
Version filter is unclear if result MUST only be the latest version

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#25]
Section 3.5.1
The version filter description says you MUST return the latest version if no version parameter is specified. It is not clear if this means MUST ONLY return the last version or if it includes the older versions so long as the latest one is also included.

**Comment by jmgnc** [comment]
I'm for returned ONLY the latest version.

**Comment by jordan2175** [comment]
We talked about this on the working call on 2018-01-23 and the consensus on that call was to change the text to say "MUST ONLY return the latest version".  No one on the call objected to making this change. The following people were on the working call: Bret Jordan, Trey Darley, John-Mark Gurney, Sarah Kelley, Chris Ricard, Dave Lemire, Jason Keirstead, Nicholas Hayden, Richard Struse, Sunil Ravipati.

**Comment by jordan2175** [comment]
The Version filter text specifies that when absent from a request, the most recent version should be returned. The text does not specify whether other versions are permitted.

The proposed change is to clarify that only the current version should be returned, and that other versions are prohibited.

**Comment by jordan2175** [comment]
This is now in section 3.4.1.  I am thinking the text needs to be something like this:

> If no version parameter is provided, the server MUST only return the latest version of the object that the server and client has access to.

**Comment by gtback** [comment]
A few questions about the `version` filter:

- Do we want to allow `first` and `last` to be combined with explicit timestamped versions (or with each other) like `?match[version]=first,last,2016-01-01T01:01:01.000Z`)? If so, we should give an example like that explicitly, otherwise we can say something like "`first`, `last`, and `all` MUST NOT be combined with each other or with specific version values."
- Can we just say that "The server must respond identically If `match[version]` is not specified, or if `match[version]=last`.?
- I don't really understand "that the server and client has access to." It gets ambiguous when making a "get objects" request that returns multiple object. In that case I assume we want it to return the latest version of each object. 

And, not to be pedantic, but I think it should be "MUST return only", not "MUST only return". 

So maybe:

> If the `version` parameter is equal to `last` or is not provided, the server MUST return exactly one version of each object matching the remainder of the request: the latest version that the client is permitted to read.

I'm not a huge fan of " that the client is permitted to read.", because the server can decide to return different results to different users for whatever reason. I wonder whether the restriction is really that a "latest" query shouldn't return an version older than one that was previously returned (unless the newer version has been removed).

**Comment by johnwunder** [comment]
+1 to this specific change. I do think some of the issues @gtback brings up should also be clarified. Specifically:

* We should prohibit first, last, all from being combined with timestamps or with each other.
* I think the text could be somewhat improved for clarity during the editorial process but overall is fine.

**Comment by jordan2175** [comment]
In section 3.4.1 the text now says:

> The version(s) of the object(s) that are being requested from either an object or manifest endpoint. If no version parameter is provided, the server MUST return only the latest version for each object matching the remainder of the request. 

> Requests MUST NOT contain any duplicate version parameters, meaning, each keyword (all, first, and last) and any specific version (<value>) MUST NOT occur more than once in a request.
