### ISSUE TITLE
Microsecond precision for date added timestamp

### ISSUE THREAD

**Issue by jordan2175** [oasis-tcs/cti-taxii2#52]
We should define that the date added property in TAXII MUST be at microsecond level precision.

**Comment by varnerac** [comment]
I'm against this. It doesn't solve time-based sorting. It only makes it _less_ bad. The HTTP libraries I use actually cache RFC 1123 formatted date-time stamps in RAM every second and pull the timestamp out of RAM rather than computing it for performance reason.

Instead, we need a way to iterate across a large result set. We can do that now:

* Collections: Collection ID
* Objects: concatenation of Object ID + modified

**Comment by jordan2175** [comment]
This came up at the F2F today in NYC. The consensus in the room is that we should probably do this. There was concern that we are too vague in the spec right now and additional text should be added.

**Comment by jordan2175** [comment]
These changes have been added to working draft 04
